// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;

public class CSV_TextTable
{
    public class Row
	{
		public string Key;
		public string fr;
		public string en;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Key = grid[i][0];
			row.fr = grid[i][1];
			row.en = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_Key(string find)
	{
		return rowList.Find(x => x.Key == find);
	}
	public List<Row> FindAll_Key(string find)
	{
		return rowList.FindAll(x => x.Key == find);
	}
	public Row Find_fr(string find)
	{
		return rowList.Find(x => x.fr == find);
	}
	public List<Row> FindAll_fr(string find)
	{
		return rowList.FindAll(x => x.fr == find);
	}
	public Row Find_en(string find)
	{
		return rowList.Find(x => x.en == find);
	}
	public List<Row> FindAll_en(string find)
	{
		return rowList.FindAll(x => x.en == find);
	}

}